-- Database: mouts

-- DROP DATABASE IF EXISTS mouts;

CREATE DATABASE mouts
    WITH
    OWNER = admin
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;



-- Table: public.products

-- DROP TABLE IF EXISTS public.products;

CREATE TABLE IF NOT EXISTS public.products
(
    id bigint NOT NULL DEFAULT nextval('products_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price numeric(38,2) NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
)

ALTER TABLE IF EXISTS public.products
    OWNER to admin;

GRANT ALL ON TABLE public.products TO admin;



	-- Table: public.orders

-- DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
    order_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(38,2) NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_code_key UNIQUE (order_code)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.orders
    OWNER to admin;

GRANT ALL ON TABLE public.orders TO admin;



	-- Table: public.order_products

-- DROP TABLE IF EXISTS public.order_products;

CREATE TABLE IF NOT EXISTS public.order_products
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    order_product_price numeric(38,2),
    CONSTRAINT order_products_pkey PRIMARY KEY (id),
    CONSTRAINT fkawxpt1ns1sr7al76nvjkv21of FOREIGN KEY (order_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdxjduvg7991r4qja26fsckxv8 FOREIGN KEY (product_id)
        REFERENCES public.products (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.order_products
    OWNER to admin;





